org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g

# Compose Multiplatform
org.jetbrains.compose.experimental.jscanvas.enabled=false
